INSERT INTO `pizzas` (`price`, `description`, `img_url`, `name`) VALUES ('10', 'Fragrante', 'https://picsum.photos/200', '4 stagioni')
INSERT INTO `pizzas` (`price`, `description`, `img_url`, `name`) VALUES ('6', 'Grande classico', 'https://picsum.photos/200', 'Margherita')
INSERT INTO `pizzas` (`price`, `description`, `img_url`, `name`) VALUES ('12', 'Formaggiosa', 'https://picsum.photos/200', '4 Formaggi')
INSERT INTO `pizzas` (`price`, `description`, `img_url`, `name`) VALUES ('8', 'Underground', 'https://picsum.photos/200', 'Capricciosa')
INSERT INTO `discounts` (`pizza_id`, `end_date`, `start_date`, `title`) VALUES (1, '2023-03-07', '2023-01-07', 'Sconto 20%')
INSERT INTO `discounts` (`pizza_id`, `end_date`, `start_date`, `title`) VALUES (2, '2023-05-07', '2023-01-07', 'Sconto 30%')
INSERT INTO `discounts` (`pizza_id`, `end_date`, `start_date`, `title`) VALUES (3, '2023-04-07', '2023-01-07', 'Sconto 40%')
INSERT INTO `discounts` (`pizza_id`, `end_date`, `start_date`, `title`) VALUES (1, '2023-05-07', '2023-04-07', 'Sconto 40%')
INSERT INTO `ingredients` (`name`) VALUES ('pomodoro')
INSERT INTO `ingredients` (`name`) VALUES ('mozzarella')
INSERT INTO `ingredients` (`name`) VALUES ('prosciutto')
INSERT INTO `ingredients` (`name`) VALUES ('funghi')
INSERT INTO `ingredients` (`name`) VALUES ('olive')
INSERT INTO `ingredients` (`name`) VALUES ('carciofi')
INSERT INTO `ingredients` (`name`) VALUES ('basilico')
INSERT INTO `ingredients` (`name`) VALUES ('gorgonzola')
INSERT INTO `ingredients` (`name`) VALUES ('fontina')
INSERT INTO `ingredients` (`name`) VALUES ('parmigiano')
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1, 1)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1, 2)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1, 3)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1, 4)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1 ,5)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1, 6)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (1, 7)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (2, 1)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (2, 2)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (2, 7)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (3, 2)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (3, 8)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (3, 9)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (3, 10)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4, 1)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4, 2)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4, 3)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4, 4)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4 ,5)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4, 6)
INSERT INTO `pizza_ingredient` (`pizza_id`, `ingredient_id`) VALUES (4, 7)
INSERT INTO roles (id, name) VALUES(1,'ADMIN');
INSERT INTO roles (id, name) VALUES(2,'USER');
INSERT INTO users (id, email, first_name, last_name, password) VALUES(1, 'admin@email.com', 'Daniel', 'Constantin', '{noop}admin');
INSERT INTO users (id, email, first_name, last_name, password) VALUES(2, 'jane@email.com', 'George', 'Constantin', '{noop}user');
INSERT INTO users_roles (roles_id, user_id) VALUES(1, 1);
INSERT INTO users_roles (roles_id, user_id) VALUES(2, 2);
